job_titles:
  - cloud
  - devops
  - aws
  - python
  - linux
  - platform engineer

skills:
  - AWS
  - Terraform
  - Docker
  - Kubernetes
  - Jenkins
  - GitLab
  - Linux
  - Python
  - Shell Scripting
  - Networking
  - Ansible

locations:
  - Bengaluru
  - Chennai
  - Coimbatore
  - Hyderabad
  - Remote

experience:
  min: 0
  max: 2
