candidate:
  name: Parameshwari V
  experience: 1

locations:
  - Bengaluru
  - Chennai
  - Coimbatore
  - Hyderabad
  - Remote

job_preferences:
  remote: true
  hybrid: true
  onsite: true

roles:
  - AWS Cloud Engineer
  - Cloud Support Engineer
  - Junior DevOps Engineer
  - DevOps Engineer
  - Linux Administrator
  - System Administrator
  - Network Engineer

approval_required: true

excel_tracker: data/applied_jobs.xlsx
